Closes #262, closes #270
TheAngryByrd/MiniScaffold pull request #271
Opened 2023-06-05 21:02 UTC by nikoyak

## Proposed Changes

Almost line by line copying of the 'build' project and GitHub Actions from TheAngryByrd/IcedTasks repository. Similar changes have been made to the Content/Library template.

## Types of changes

What types of changes does your code introduce to MiniScaffold?

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] Build and tests pass locally
- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have added necessary documentation (if appropriate)

## Further comments

Tests had to be corrected.

2023-06-05 21:25 UTC, TheAngryByrd commented
Thank you so much for this! I'll start reviewing it later tonight.

2023-06-06 06:03 UTC, nikoyak commented
Sorry I didn't test CI build. Fixed.

2023-06-06 15:56 UTC, TheAngryByrd requested changes
Thank you so much for this!

One thing I'd like to revert/change listed in the feedback.

2023-06-06 15:56 UTC, TheAngryByrd commented on Content/Library/build/Changelog.fs
Could you revert the changes to Changelog.fs to keep it in a separate file? Might involve dealing with some unpleasant merging though.

2023-06-06 21:40 UTC, nikoyak commented on Content/Library/build/Changelog.fs
Done.

2023-06-07 01:23 UTC, TheAngryByrd approved these changes

2023-06-07 01:23 UTC, merged