Coverage report tweaks
TheAngryByrd/MiniScaffold pull request #272
Opened 2023-06-08 11:13 UTC by nikoyak

## Proposed Changes
This PR:
- Restores the GenerateCoverageReport dependency chain broken in #271
- Сloses #251
- Adds the handy ShowCoverageReport target  to the library template 

## Types of changes

What types of changes does your code introduce to MiniScaffold?

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] Build and tests pass locally
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Further comments

Unclosed question on test coverage verification. It is not necessary to evaluate test coverage every time you run tests, and to speed up feedback, it is inconvenient to write the `cmd /c "set DISABLE_COVERAGE=1& build DotnetTest"` command on Windows, for example. I propose to change the logic and replacing the environment variable with ENABLE_COVERAGE. And local testing with test coverage is convenient to do with a new ShowCoverageReport target. What do you think?

2023-06-08 13:55 UTC, TheAngryByrd requested changes

2023-06-08 13:55 UTC, TheAngryByrd commented on Content/Library/build/build.fs
> +    |> ignore
I seem to remember this won't work on osx/linux.

2023-06-08 14:00 UTC, baronfel commented on Content/Library/build/build.fs
> +    |> ignore
So long as UseShellExecute is set to true this should work. The Runtime used xdg-open or equivalent to launch the configured handler for the file: https://github.com/dotnet/runtime/blob/main/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.Linux.cs#L108

2023-06-08 14:05 UTC, TheAngryByrd commented on Content/Library/build/build.fs
> +    |> ignore
Oh that's awesome.

https://github.com/fsprojects/FAKE/blob/13e30330cae0597aed6154a95a06d21716b18de3/src/app/Fake.Core.Process/RawProc.fs#L163 looks like `Command.ShellCommand` will do it.

2023-06-08 14:05 UTC, TheAngryByrd approved these changes
Want me to merge this or wait for the `ENABLE_COVERAGE` change?

2023-06-08 15:26 UTC, nikoyak commented
> Want me to merge this or wait for the `ENABLE_COVERAGE` change?
Wait

2023-06-09 19:31 UTC, TheAngryByrd approved these changes

2023-06-09 19:31 UTC, merged